version: '3'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file: .env
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  ide:
    container_name: ide
    env_file: .env
    volumes:
      - ./ide:/root/project
    ports:
      - 8443
    restart: unless-stopped